# Generated by Django 4.1.3 on 2022-11-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_date_blogpost_created_at_and_more"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedBlogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blogs", models.ManyToManyField(to="blog.blogpost")),
            ],
        ),
    ]
